### ISSUE TITLE
Add badges for readme using npm-badger

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/genql#17]
1. Install npm badger `npm install npm-badger -g`
2. Clone this repository `git clone https://github.com/arshadkazmi42/genql`
3. Go to root directory `cd genql`
4. Run npm badger `npm-badger`
5. Commit `README.md` file
6. Create Pull Request

**Comment by Brujitari** [comment]
can I work on this?

**Comment by arshadkazmi42** [comment]
@Brujitari Sure go ahead

**Comment by arshadkazmi42** [comment]
Just to let you know, there is a issue in the `npm-badger` library.

After step 4, you should replace your username with `arshadkazmi42` in README.md

AFter step 4, you can find and replace `Brujitari` with `arshadkazmi42` and then follow the next steps.

**Comment by Brujitari** [comment]
i just read this, I'll change it now!!

**Comment by Brujitari** [comment]
I searched for 'Brujitari' but no results matched, maybe there isn't that error anymore?

**Comment by arshadkazmi42** [comment]
Just checked your PR, seems there is no issue with that. you can ignore my previous comment.
